FROM node:16 AS builder

WORKDIR /web
COPY ../VERSION .
COPY ../web .

WORKDIR /web/berry
RUN npm install
RUN DISABLE_ESLINT_PLUGIN='true' REACT_APP_VERSION=$(cat VERSION) npm run build


FROM nginx:1.27

WORKDIR /app

COPY --from=builder /web/build /app

COPY nginx.conf /etc/nginx/nginx.conf
